In [2]:
import pandas as pd

demand = pd.read_csv(
    r"D:\MScProjects\labour-market-intelligence\data\processed\digital_demand_2023_2025.csv"
)

demand["Month"] = pd.to_datetime(demand["Month"])

demand.head()

,Month,2134 Programmers and software development professionals,2135 Cyber security professionals,"2433 Actuaries, economists and statisticians",3133 Database administrators and web content technicians,3544 Data analysts
0,2023-01-01,25269.0,3712.0,3993.0,2397.0,3606.0
1,2023-02-01,25118.0,3367.0,3131.0,2084.0,3358.0
2,2023-03-01,21905.0,3073.0,2908.0,1883.0,3261.0
3,2023-04-01,15409.0,2511.0,2473.0,1507.0,2462.0
4,2023-05-01,17787.0,2923.0,3069.0,1958.0,2962.0

In [3]:
demand = demand.rename(columns={
    "2134 Programmers and software development professionals":
        "Programmers and software development professionals",

    "2135 Cyber security professionals":
        "Cyber security professionals",

    "2433 Actuaries, economists and statisticians":
        "Actuaries, economists and statisticians",

    "3133 Database administrators and web content technicians":
        "Database administrators and web content technicians",

    "3544 Data analysts":
        "Data analysts"
})

In [4]:
demand_long = demand.melt(
    id_vars="Month",
    var_name="Occupation",
    value_name="Demand"
)

print(demand_long.shape)
demand_long.head()

(145, 3)

       Month                                         Occupation   Demand
0 2023-01-01  Programmers and software development professio...  25269.0
1 2023-02-01  Programmers and software development professio...  25118.0
2 2023-03-01  Programmers and software development professio...  21905.0
3 2023-04-01  Programmers and software development professio...  15409.0
4 2023-05-01  Programmers and software development professio...  17787.0

In [5]:
print(demand_long["Occupation"].unique())
print(salary_long["Occupation"].unique())

<ArrowStringArray>
[ 'Programmers and software development professionals',
                        'Cyber security professionals',
             'Actuaries, economists and statisticians',
 'Database administrators and web content technicians',
                                       'Data analysts']
Length: 5, dtype: str

NameError: name 'salary_long' is not defined

In [6]:
print(salary_long["Occupation"].unique())

NameError: name 'salary_long' is not defined

In [7]:
import pandas as pd

salary_long = pd.read_csv(
    r"D:\MScProjects\labour-market-intelligence\data\processed\salary_2023_2025.csv"
)

salary_long["Month"] = pd.to_datetime(salary_long["Month"])

print(salary_long.shape)
salary_long.head()

(145, 4)

,SOC_Code,Occupation,Month,Median_Salary
0,2134.0,Programmers and software development professio...,2023-01-01,52500
1,2135.0,Cyber security professionals,2023-01-01,55000
2,2433.0,"Actuaries, economists and statisticians",2023-01-01,55000
3,3133.0,Database administrators and web content techni...,2023-01-01,30000
4,3544.0,Data analysts,2023-01-01,39000

In [8]:
print(salary_long["Occupation"].unique())

<ArrowStringArray>
[ 'Programmers and software development professionals',
                        'Cyber security professionals',
             'Actuaries, economists and statisticians',
 'Database administrators and web content technicians',
                                       'Data analysts']
Length: 5, dtype: str

In [9]:
master_df = pd.merge(
    demand_long,
    salary_long,
    on=["Month", "Occupation"],
    how="inner"
)

print(master_df.shape)
master_df.head()

(145, 5)

,Month,Occupation,Demand,SOC_Code,Median_Salary
0,2023-01-01,Programmers and software development professio...,25269.0,2134.0,52500
1,2023-02-01,Programmers and software development professio...,25118.0,2134.0,55000
2,2023-03-01,Programmers and software development professio...,21905.0,2134.0,55000
3,2023-04-01,Programmers and software development professio...,15409.0,2134.0,55000
4,2023-05-01,Programmers and software development professio...,17787.0,2134.0,55000

In [10]:
output_path = r"D:\MScProjects\labour-market-intelligence\data\processed\master_dataset.csv"

master_df.to_csv(output_path, index=False)

print("Master dataset saved successfully!")

Master dataset saved successfully!

In [11]:
master_df.info()

master_df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Month          145 non-null    datetime64[us]
 1   Occupation     145 non-null    str
 2   Demand         145 non-null    float64
 3   SOC_Code       145 non-null    float64
 4   Median_Salary  145 non-null    int64
dtypes: datetime64[us](1), float64(2), int64(1), str(1)
memory usage: 10.9 KB

Month            0
Occupation       0
Demand           0
SOC_Code         0
Median_Salary    0
dtype: int64