In [3]:
import pandas as pd

skills = pd.read_excel(
    r"D:\MScProjects\labour-market-intelligence\data\raw\onet\Essential Skills.xlsx"
)

print(skills.shape)
skills.head()

(17880, 15)

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.1830,4.2664,4.9836,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.1637,4.4292,5.0708,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.1250,3.8800,4.3700,N,NaN,08/2023,Analyst

In [4]:
print(skills.columns.tolist())

['O*NET-SOC Code', 'Title', 'Element ID', 'Element Name', 'Scale ID', 'Scale Name', 'Data Value', 'N', 'Standard Error', 'Lower CI Bound', 'Upper CI Bound', 'Recommend Suppress', 'Not Relevant', 'Date', 'Domain Source']

In [5]:
skills["Title"].unique()[:20]

<ArrowStringArray>
[                         'Chief Executives',
             'Chief Sustainability Officers',
           'General and Operations Managers',
       'Advertising and Promotions Managers',
                        'Marketing Managers',
                            'Sales Managers',
                      'Fundraising Managers',
          'Administrative Services Managers',
                       'Facilities Managers',
                         'Security Managers',
 'Computer and Information Systems Managers',
                        'Financial Managers',
                'Treasurers and Controllers',
                  'Investment Fund Managers',
            'Industrial Production Managers',
          'Quality Control Systems Managers',
            'Geothermal Production Managers',
              'Biofuels Production Managers',
              'Biomass Power Plant Managers',
         'Hydroelectric Production Managers']
Length: 20, dtype: str

In [6]:
skills[
    skills["Title"].str.contains(
        "Software|Cyber|Data|Database|Statistic",
        case=False,
        na=False
    )
][["O*NET-SOC Code","Title"]].drop_duplicates()

      O*NET-SOC Code                                            Title
2140      15-1242.00                          Database Administrators
2160      15-1243.00                              Database Architects
2180      15-1243.01                     Data Warehousing Specialists
2240      15-1252.00                              Software Developers
2260      15-1253.00  Software Quality Assurance Analysts and Testers
2500      15-2041.00                                    Statisticians
2520      15-2041.01                                 Biostatisticians
2560      15-2051.02                           Clinical Data Managers
12120     43-9021.00                                Data Entry Keyers
12280     43-9111.00                           Statistical Assistants

In [7]:
selected_skills = skills[
    skills["Title"].isin([
        "Software Developers",
        "Information Security Analysts",
        "Data Scientists",
        "Database Administrators",
        "Statisticians"
    ])
].copy()

print(selected_skills.shape)
selected_skills.head()

(80, 15)

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
2020,15-1212.00,Information Security Analysts,2.A.1.a,Reading Comprehension,IM,Importance,4.00,8,0.0000,4.0000,4.0000,N,NaN,08/2018,Analyst
2021,15-1212.00,Information Security Analysts,2.A.1.a,Reading Comprehension,LV,Level,4.12,8,0.1250,3.8800,4.3700,N,N,08/2018,Analyst
2022,15-1212.00,Information Security Analysts,2.A.1.b,Active Listening,IM,Importance,3.75,8,0.1637,3.4292,4.0708,N,NaN,08/2018,Analyst
2023,15-1212.00,Information Security Analysts,2.A.1.b,Active Listening,LV,Level,3.88,8,0.1250,3.6300,4.1200,N,N,08/2018,Analyst
2024,15-1212.00,Information Security Analysts,2.A.1.c,Writing,IM,Importance,3.50,8,0.1890,3.1296,3.8704,N,NaN,08/2018,Analyst

In [8]:
selected_skills = selected_skills[
    [
        "Title",
        "Element Name",
        "Scale Name",
        "Data Value"
    ]
]

selected_skills.head()

,Title,Element Name,Scale Name,Data Value
2020,Information Security Analysts,Reading Comprehension,Importance,4.00
2021,Information Security Analysts,Reading Comprehension,Level,4.12
2022,Information Security Analysts,Active Listening,Importance,3.75
2023,Information Security Analysts,Active Listening,Level,3.88
2024,Information Security Analysts,Writing,Importance,3.50

In [9]:
selected_skills.to_csv(
    r"D:\MScProjects\labour-market-intelligence\data\processed\onet_selected_skills.csv",
    index=False
)